Тестовий переклад Констант
levonet/arduino-reference-uk pull request #2
Opened 2021-02-16 19:31 UTC by BatsIhor

Англійський текст залишений для порівняння перекладу з оригіналом.

2021-02-20 16:44 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +== Визначення Рівня Піну: HIGH або LOW
Про `пін` потрібно домовитись та використовувати у всіх документах однаковий термін. Я вже почав використовувати контакт, але досі не визначився як верніше, бо не вистачає кворуму )

2021-02-20 17:09 UTC, levonet requested changes

2021-02-20 17:09 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +
Нижче

2021-02-20 17:09 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +У випадках коли пін сконфігурований як OUTPUT(вихід) через фенкцію link:../../../functions/digital-io/pinmode[`pinMode()`], і його значення задане як `HIGH` задопомогою link:../../../functions/digita
Функцію

2021-02-20 17:09 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Якщо ти маєш пін налаштований як `INPUT`, і зчитуєш дані з перемикача, в випадку коли перемикач розімкнутий стан піну буде "літати"("floating"), як результат зчитані дані будуть непередбачувані. Для
Мабуть не літати, а плавати, бо стан буде невизначений

2021-02-20 17:09 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Якщо ти маєш пін налаштований як `INPUT`, і зчитуєш дані з перемикача, в випадку коли перемикач розімкнутий стан піну буде "літати"("floating"), як результат зчитані дані будуть непередбачувані. Для
Ще одна пропозиція, робити одне речення на рядок. Бо інакше складно коментувати щось. Тут маю зауваження до формулювання деяких речень, але зараз з телефону, тому прокоментую окремо, пізніше

2021-02-22 19:50 UTC, BatsIhor commented on Language/Variables/Constants/constants.adoc
> +== Визначення Рівня Піну: HIGH або LOW
Добре в подальшому буду використовувати Контакт

2021-02-22 20:21 UTC, BatsIhor commented on Language/Variables/Constants/constants.adoc
> +Якщо ти маєш пін налаштований як `INPUT`, і зчитуєш дані з перемикача, в випадку коли перемикач розімкнутий стан піну буде "літати"("floating"), як результат зчитані дані будуть непередбачувані. Для
Кожне речення на окремому рядку.

2021-02-23 21:58 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Вони використовуютсья для того, щоб спростити читання програми.
використовуються

2021-02-23 22:02 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Контакт також може бути налаштованим як Вхід(INPUT) задопомогою link:../../../functions/digital-io/pinmode[`pinMode()`], і в подальшому переведений в стан HIGH задопомогою `link:../../../functions/di
за допомогою *2

2021-02-23 22:05 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +У випадках коли контакт сконфігурований як OUTPUT(вихід) через функцію link:../../../functions/digital-io/pinmode[`pinMode()`], і його значення задане як `HIGH` задопомогою link:../../../functions/di
за допомогою

2021-02-23 22:09 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Коли контакт сконфігурований як `OUTPUT` задопомогою link:../../../functions/digital-io/pinmode[`pinMode()`], та його стан заданий як `LOW` використовуючи link:../../../functions/digital-io/digitalwr
за допомогою

2021-02-23 22:11 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +В цьому стані контакт може проводити струм до мінусу, доприкладу засвічувати LED який є підклюеним до живлення +5 вольт (або +3.3 вольт) через опір.
~~доприкладу~~ наприклад
~~підклюеним~~ підключеним

2021-02-23 22:12 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +== Встановлення стану Цифрового контакту: INPUT, INPUT_PULLUP, and OUTPUT
~~and~~ та

2021-02-23 22:16 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Метою цього опору є підтягування контакту до необіхного значення у випадках коли контакт не підключений.
необхідного

2021-02-23 22:17 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Зазвичай використовують 10К опір, так як його значення є достатньо малим для того, щоб контакт не "плавав" і в той самий час його значення достатньо велике, щоб не пропускати занадто багато стурму ко
струму

2021-02-23 22:19 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Якщо використовуєтсья контактижуючий опір, вихдний контакт буде `LOW` в випадках коли перемикач на його кінці розімкнутий і `HIGH` коли перемикач замкнутий.
~~контактижуючий~~  понижуючий?

2021-02-23 22:20 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Якщо використовуєтсья контактижуючий опір, вихдний контакт буде `LOW` в випадках коли перемикач на його кінці розімкнутий і `HIGH` коли перемикач замкнутий.
використовується

2021-02-23 22:20 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Якщо використовуєтсья підтягуючий опір, вхідний контакт буде в стані `HIGH` коли перемикач розімкнутий та в `LOW` стані коли перемикач замкнутий.
використовується

2021-02-23 22:21 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Мікроконтроллер ATmega на Андруіно має внутрішній підтягуючий опір (опір підключений до живлення) який ти можеш використати.
Мікроконтролер

2021-02-23 22:24 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Контакти налаштовані як вхідні з допомогою `INPUT` або `INPUT_PULLUP` можуть бути зруйнованими якщо підключені до напруги нищої 0(негативної напруги) або вище додатньої межі (5V або 3V).
нижчої
~~вище додатньої межі~~ вище позитивної межі

2021-02-23 22:27 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Більшість Ардуіно плат мають контакт підключений до вмонованого на плату LED через опір.
вмонтованого

2021-02-23 22:27 UTC, levonet commented on Language/Variables/Constants/constants.adoc
> +Більшість плат мають цей LED підключеним до вифрового контакту 13.
цифрового

2021-02-23 22:40 UTC, levonet commented
Я тобі надав доступ до репо. Тому пропоную робити зміни не з форка, а безпосередньо в цьому рєпо з гілок.
Таким чином якись правки яб зміг вносити в твій переклад, чи навпаки, ти в мій.

На гілку master ствлю захист. Бо ти вже встиг вмержити в неї свої зміни минуючи ПР, через що виник мерджконфлікт.
Зміни в мастер я відкотив.

2021-03-05 22:09 UTC, merged